language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  # - docker build -t simple-node .
  # - docker build -t simple-node --build-arg NAME=${NAME} .
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy

  # Tagging
  - docker tag udagram-api-feed minhnk/udagram-api-feed:v2
  - docker tag udagram-api-user minhnk/udagram-api-user:v2
  - docker tag udagram-frontend minhnk/udagram-frontend:v2
  - docker tag reverseproxy minhnk/reverseproxy:v2
  # - docker tag simple-node minhnk/simple-node:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push minhnk/udagram-api-feed:v2
  - docker push minhnk/udagram-api-user:v2
  - docker push minhnk/udagram-frontend:v2
  - docker push minhnk/reverseproxy:v2
  # - docker push minhnk/simple-node
